spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homedb
    username: home
    password: home_db_password_123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8082

app:
  mqtt:
    broker-url: ${MQTT_BROKER_URL:tcp://home.sebi4.com:1883}
    username: ${MQTT_USERNAME:homeassistant}
    password: ${MQTT_PASSWORD:S4Bi2OO5}
